export const CLONE_LAST_BEFORE_FIRST = 'CLONE_LAST_BEFORE_FIRST';
export const CLONE_FIRST_AFTER_LAST = 'CLONE_FIRST_AFTER_LAST';
export const REMOVE_FIRST = 'REMOVE_FIRST';
export const REMOVE_LAST = 'REMOVE_LAST';

export const ADD_NEW_ITEM = 'ADD_NEW_ITEM';
